-- Run this entire file to enable Store Reviews

-- Create a table for store reviews
create table if not exists public.store_reviews (
  id bigint generated by default as identity primary key,
  store_id bigint not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  content text,
  rating integer check (rating >= 1 and rating <= 5) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.store_reviews enable row level security;

-- Policies (We drop them first to allow re-running this script without errors)

drop policy if exists "Reviews are viewable by everyone." on store_reviews;
create policy "Reviews are viewable by everyone."
  on store_reviews for select
  using ( true );

drop policy if exists "Authenticated users can insert reviews." on store_reviews;
create policy "Authenticated users can insert reviews."
  on store_reviews for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "Users can update own reviews." on store_reviews;
create policy "Users can update own reviews."
  on store_reviews for update
  using ( auth.uid() = user_id );

drop policy if exists "Users can delete own reviews." on store_reviews;
create policy "Users can delete own reviews."
  on store_reviews for delete
  using ( auth.uid() = user_id );
