-- Create table for real-time store status logs
create table if not exists public.store_status_logs (
  id bigint generated by default as identity primary key,
  store_id bigint not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  status text check (status in ('OPEN', 'CLOSED', 'OUT_OF_STOCK')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.store_status_logs enable row level security;

-- Policies
drop policy if exists "Status logs are viewable by everyone." on store_status_logs;
create policy "Status logs are viewable by everyone."
  on store_status_logs for select
  using ( true );

drop policy if exists "Authenticated users can insert status logs." on store_status_logs;
create policy "Authenticated users can insert status logs."
  on store_status_logs for insert
  with check ( auth.role() = 'authenticated' );
