-- Create a table for public profiles using the auth.users table
create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  full_name text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table public.profiles enable row level security;

drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for posts
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.posts enable row level security;

drop policy if exists "Posts are viewable by everyone." on posts;
create policy "Posts are viewable by everyone."
  on posts for select
  using ( true );

drop policy if exists "Authenticated users can insert posts." on posts;
create policy "Authenticated users can insert posts."
  on posts for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "Users can update own posts." on posts;
create policy "Users can update own posts."
  on posts for update
  using ( auth.uid() = user_id );

drop policy if exists "Users can delete own posts." on posts;
create policy "Users can delete own posts."
  on posts for delete
  using ( auth.uid() = user_id );

-- Create a table for comments
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.comments enable row level security;

drop policy if exists "Comments are viewable by everyone." on comments;
create policy "Comments are viewable by everyone."
  on comments for select
  using ( true );

drop policy if exists "Authenticated users can insert comments." on comments;
create policy "Authenticated users can insert comments."
  on comments for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "Users can update own comments." on comments;
create policy "Users can update own comments."
  on comments for update
  using ( auth.uid() = user_id );

drop policy if exists "Users can delete own comments." on comments;
create policy "Users can delete own comments."
  on comments for delete
  using ( auth.uid() = user_id );

-- Function to handle new user creation
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, username)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
-- Drop trigger first to avoid "already exists" error
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create a table for store reviews
create table if not exists public.store_reviews (
  id bigint generated by default as identity primary key,
  store_id bigint not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  content text,
  rating integer check (rating >= 1 and rating <= 5) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.store_reviews enable row level security;

drop policy if exists "Reviews are viewable by everyone." on store_reviews;
create policy "Reviews are viewable by everyone."
  on store_reviews for select
  using ( true );

drop policy if exists "Authenticated users can insert reviews." on store_reviews;
create policy "Authenticated users can insert reviews."
  on store_reviews for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "Users can update own reviews." on store_reviews;
create policy "Users can update own reviews."
  on store_reviews for update
  using ( auth.uid() = user_id );

drop policy if exists "Users can delete own reviews." on store_reviews;
create policy "Users can delete own reviews."
  on store_reviews for delete
  using ( auth.uid() = user_id );
